import 'package:thunder_app/Models/company_model.dart';

List<CompanyModel> myCompanies = [
  CompanyModel(
      companyName: 'Abu Qir Fertilizers and Chemicals',
      shortName: 'ABUK',
      image: 'images/ABUK.png',
      descriptionImage: 'images/aboqir_des.jpg',
      marketCap: '71.93b',
      earnings: '4.56x',
      dividendYield: '13.23%',
      avgTradedValue: '90.72m',
      price: 57.00,
      eps: 11.60,
      valueToday: '161.11m',
      increaseEGP: 4.09,
      increaseAverage: 7.73),
  CompanyModel(
      companyName: 'Abu Dhabi Islamic Bank - Egypt',
      shortName: 'ADIB',
      image: 'images/Abu_Dhabi_Islamic_Bank.jpg',
      descriptionImage: 'images/abodhabi_des.jpg',
      marketCap: '19.42b',
      earnings: '4.01x',
      dividendYield: 'N/A',
      avgTradedValue: '33.50m',
      price: 38.84,
      eps: 9.35,
      valueToday: '10.65m',
      increaseEGP: 1.37,
      increaseAverage: 3.66),
  CompanyModel(
      companyName: 'Alexandria Container & Cargo Handling Company',
      shortName: 'ALCN',
      image: 'images/alexcont.png',
      descriptionImage: 'images/alex_des.jpg',
      marketCap: '56.31b',
      earnings: '12.66x',
      dividendYield: '5.19%',
      avgTradedValue: '39.23m',
      price: 37.80,
      eps: 2.95,
      valueToday: '10.89m',
      increaseAverage: 1.39,
      increaseEGP: 0.52),
  CompanyModel(
      companyName: 'Alexandria Mineral Oils Company',
      shortName: 'AMOC',
      image: 'images/amoc.png',
      descriptionImage: 'images/alexoil_des.jpg',
      marketCap: '11.88b',
      earnings: '8.57x',
      dividendYield: '7.14%',
      avgTradedValue: '52.07m',
      price: 9.20,
      eps: 1.06,
      valueToday: '39.53m',
      increaseAverage: 1.10,
      increaseEGP: 0.10),
  CompanyModel(
      companyName: 'Beltone Financial',
      shortName: 'BTFH',
      image: 'images/beltone.png',
      descriptionImage: 'images/beltone-des.jpg',
      marketCap: '15.52b',
      earnings: '42.17x',
      dividendYield: 'N/A',
      avgTradedValue: '240.85m',
      price: 2.84,
      eps: 0.07,
      valueToday: '64.15m',
      decreaseAverage: -0.35,
      decreaseEGP: 0.01),
  CompanyModel(
      companyName: 'Commercial International Bank',
      shortName: 'COMI',
      image: 'images/commercialbank.png',
      descriptionImage: 'images/cip-des.jpg',
      marketCap: '225.19b',
      earnings: '7.59x',
      dividendYield: '0.74%',
      avgTradedValue: '471.76m',
      price: 74.00,
      eps: 9.75,
      valueToday: '397.03m'),
  CompanyModel(
      companyName: 'Eastern Company',
      shortName: 'EAST',
      image: 'images/eastren.jpeg',
      descriptionImage: 'images/estern_des.jpg',
      marketCap: '51.15b',
      earnings: '13.40x',
      dividendYield: '20.83%',
      avgTradedValue: '44.23m',
      price: 17.05,
      eps: 1.34,
      valueToday: '101.16m',
      decreaseAverage: -5.28,
      decreaseEGP: 0.95),
  CompanyModel(
      companyName: 'Edita Food Industries',
      shortName: 'EFID',
      image: 'images/edita.png',
      descriptionImage: 'images/edita_des.jpg',
      marketCap: '20.65b',
      earnings: '12.59x',
      dividendYield: '1.48%',
      avgTradedValue: '16.24m',
      price: 29.51,
      eps: 2.30,
      valueToday: '20.14m',
      increaseAverage: 1.72,
      increaseEGP: 0.50),
  CompanyModel(
      companyName: 'EFG Holding',
      shortName: 'HRHO',
      image: 'images/hrho.webp',
      descriptionImage: 'images/efg-des.jpg',
      marketCap: '25.40b',
      earnings: '7.87x',
      dividendYield: 'N/A',
      avgTradedValue: '158.79m',
      price: 17.40,
      eps: 2.17,
      valueToday: '91.64m',
      increaseAverage: 1.75,
      increaseEGP: 0.30),
  CompanyModel(
      companyName: 'E-Finance For Digital and Financial Investements',
      shortName: 'EFIH',
      image: 'images/EFIH.jpeg',
      descriptionImage: 'images/efinance-des.jpg',
      marketCap: '45.28b',
      earnings: '34.88x',
      dividendYield: '0.79%',
      avgTradedValue: '54.70m',
      price: 24.49,
      eps: 0.69,
      valueToday: '38.40m',
      increaseAverage: 2.47,
      increaseEGP: 0.59),
  CompanyModel(
      companyName: 'Egyptian Kuwaiti Holding - (USD)',
      shortName: 'EKHO',
      image: 'images/Egypt-Kuwait-Holding-1.jpg',
      descriptionImage: 'images/ekho-des.jpg',
      marketCap: '878.97m',
      earnings: '4.05x',
      dividendYield: '7.67%',
      avgTradedValue: '11.57m',
      price: 0.780,
      eps: 0.19,
      valueToday: '115.77k',
      decreaseAverage: -0.26,
      decreaseEGP: 0.002),
  CompanyModel(
      companyName: 'Egyptian Kuwaiti Holding (EGP)',
      shortName: 'EKHOA',
      image: 'images/Egypt-Kuwait-Holding-1.jpg',
      descriptionImage: 'images/ekhoca-des.jpg',
      marketCap: '32.84b',
      earnings: '3.20x',
      dividendYield: '9.77%',
      avgTradedValue: '50.99m',
      price: 29.14,
      eps: 0.19,
      valueToday: '53.38m',
      decreaseAverage: -1.02,
      decreaseEGP: 0.30),
  CompanyModel(
      companyName: 'Elsewedy Electric',
      shortName: 'SWDY',
      image: 'images/elsewedyelectric.png',
      descriptionImage: 'images/swedy-des.jpg',
      marketCap: '102.03b',
      earnings: '9.16x',
      dividendYield: '1.06%',
      avgTradedValue: '172.33m',
      price: 47.00,
      eps: 5.13,
      valueToday: '150.76m',
      decreaseAverage: -0.04,
      decreaseEGP: 0.02),
  CompanyModel(
      companyName: 'Ezz Steel',
      shortName: 'ESRS',
      image: 'images/ezzsteel.png',
      descriptionImage: 'images/ezz-des.jpg',
      marketCap: '42.65b',
      earnings: 'N/A',
      dividendYield: 'N/A',
      avgTradedValue: '103.34m',
      price: 78.50,
      eps: -1.32,
      valueToday: '11.58m',
      increaseAverage: 4.82,
      increaseEGP: 3.61),
  CompanyModel(
      companyName: 'Fawry For Banking Technology And Electronic Payment',
      shortName: 'FWRY',
      image: 'images/fawry.jpeg',
      descriptionImage: 'images/fawry-des.jpg',
      marketCap: '19.25b',
      earnings: '23.34x',
      dividendYield: 'N/A',
      avgTradedValue: '110.19m',
      price: 5.65,
      eps: 0.24,
      valueToday: '39.42m',
      increaseAverage: 1.07,
      increaseEGP: 0.06),
  CompanyModel(
      companyName: 'GB Corp',
      shortName: 'GBCO',
      image: 'images/gbco.png',
      descriptionImage: 'images/gbco-des.jpg',
      marketCap: '12.72b',
      earnings: '6.80x',
      dividendYield: '1.76%',
      avgTradedValue: '34.79m',
      price: 11.72,
      eps: 1.67,
      valueToday: '2.93m',
      increaseAverage: 3.26,
      increaseEGP: 0.37),
  CompanyModel(
      companyName: 'Heliopolis Housing',
      shortName: 'HELI',
      image: 'images/heli.png',
      descriptionImage: 'images/heli-des.jpg',
      marketCap: '12.95b',
      earnings: '1.66x',
      dividendYield: 'N/A',
      avgTradedValue: '94.53m',
      price: 9.70,
      eps: 5.85,
      valueToday: '52.51m'),
  CompanyModel(
      companyName: 'Juhayna Food Industries',
      shortName: 'JUFO',
      image: 'images/juhayna.png',
      descriptionImage: 'images/juhayna-des.jpg',
      marketCap: '16.65b',
      earnings: '16.6x',
      dividendYield: '1.15%',
      avgTradedValue: '20.85m',
      price: 17.69,
      eps: 1.09,
      valueToday: '9.49m',
      increaseAverage: 1.49,
      increaseEGP: 0.26),
  CompanyModel(
      companyName: 'Madinet Masr For Housing and Development',
      shortName: 'MASR',
      image: 'images/masr.jpeg',
      descriptionImage: 'images/masr-des.jpg',
      marketCap: '7.69b',
      earnings: '3.57x',
      dividendYield: '5.60%',
      avgTradedValue: '55.19m',
      price: 3.73,
      eps: 1.00,
      valueToday: '35.45m',
      increaseAverage: 4.48,
      increaseEGP: 0.16),
  CompanyModel(
      companyName: 'Misr Fertilizers Production',
      shortName: 'MFPC',
      image: 'images/mopco.jpeg',
      descriptionImage: 'images/mfpc-des.jpg',
      marketCap: '89.36b',
      earnings: '14.44x',
      dividendYield: '4.82%',
      avgTradedValue: '138.26m',
      price: 42.98,
      eps: 2.87,
      valueToday: '63.96m',increaseAverage: 3.57,increaseEGP: 1.48),
  CompanyModel(
      companyName: 'Orascom Construction PLC',
      shortName: 'ORAS',
      image: 'images/Orascom.png',
      descriptionImage: 'images/oras-des.jpg',
      marketCap: '29.88b',
      earnings: '6.44x',
      dividendYield: '2.18%',
      avgTradedValue: '71.56m',
      price: 271.00,
      eps: 0.88,
      valueToday: '31.66m',increaseAverage: 0.41,increaseEGP: 1.11),
  CompanyModel(
      companyName: 'Orascom Development Egypt',
      shortName: 'ORHD',
      image: 'images/oras-dev.png',
      descriptionImage: 'images/orhd-des.jpg',
      marketCap: '11.87b',
      earnings: '3.80x',
      dividendYield: 'N/A',
      avgTradedValue: '42.27m',
      price: 10.50,
      eps: 2.76,
      valueToday: '8.17m',increaseAverage: 0.10,increaseEGP: 0.01),
  CompanyModel(
      companyName: 'Oriental Weavers',
      shortName: 'ORWE',
      image: 'images/oriental.jpeg',
      descriptionImage: 'images/orwe-des.jpg',
      marketCap: '14.75b',
      earnings: '7.57x',
      dividendYield: '5.81%',
      avgTradedValue: '42.94m',
      price: 22.18,
      eps: 2.84,
      valueToday: '27.75m',increaseAverage: 3.07,increaseEGP: 0.66),
  CompanyModel(
      companyName: 'Palm Hills Developments',
      shortName: 'PHDC',
      image: 'images/palmhils.png',
      descriptionImage: 'images/palm-des.jpg',
      marketCap: '11.80b',
      earnings: '6.86x',
      dividendYield: 'N/A',
      avgTradedValue: '110.38m',
      price: 4.01,
      eps: 0.59,
      valueToday: '145.22m',decreaseAverage: -0.74,decreaseEGP: 0.03),
  CompanyModel(
      companyName: 'Citadel Capital',
      shortName: 'CCAP',
      image: 'images/citadel.jpg',
      descriptionImage: 'images/ccap-des.jpg',
      marketCap: '2.59b',
      earnings: '0.22x',
      dividendYield: 'N/A',
      avgTradedValue: '149.01m',
      price: 1.825,
      eps: 8.32,
      valueToday: '37.44m',increaseAverage: 0.83,increaseEGP: 0.015),
  CompanyModel(
      companyName: 'Sidi Kerir Petrochemicals',
      shortName: 'SKPC',
      image: 'images/sidi.jpeg',
      descriptionImage: 'images/skpc-des.jpg',
      marketCap: '20.94b',
      earnings: '8.33x',
      dividendYield: '4.61%',
      avgTradedValue: '73.82m',
      price: 27.70,
      eps: 3.25,
      valueToday: '38.71m',increaseAverage: 2.25,increaseEGP: 0.61),
  CompanyModel(
      companyName: 'Talaat Moustafa Group',
      shortName: 'TMGH',
      image: 'images/talaat.png',
      descriptionImage: 'images/talaat-des.jpg',
      marketCap: '112.46b',
      earnings: '32.92x',
      dividendYield: '0.41%',
      avgTradedValue: '392.49m',
      price: 54.50,
      eps: 1.62,
      valueToday: '311.32m',increaseAverage: 2.06,increaseEGP: 1.10),
  CompanyModel(
      companyName: 'Telecom Egypt',
      shortName: 'ETEL',
      image: 'images/telecom_egypt.png',
      descriptionImage: 'images/telecom-des.jpg',
      marketCap: '51.55b',
      earnings: '4.39x',
      dividendYield: '5.09%',
      avgTradedValue: '50.37m',
      price: 30.20,
      eps: 6.72,
      valueToday: '9.50m',
      increaseAverage: 2.44,increaseEGP: 0.72),
  CompanyModel(
      companyName: 'Egyptian International Pharmaceuticals (EIPICO)',
      shortName: 'PHAR',
      image: 'images/eipico.jpeg',
      descriptionImage: 'images/phar-des.jpg',
      marketCap: '5.43b',
      earnings: '6.52x',
      dividendYield: '5.55%',
      avgTradedValue: '27.60m',
      price: 36.47,
      eps: 5.53,
      valueToday: '5.03m',
      increaseAverage: 1.14,increaseEGP: 0.41),
  CompanyModel(
      companyName: 'Ibnsina Pharma',
      shortName: 'ISPH',
      image: 'images/ibnsina.jpg',
      descriptionImage: 'images/ibnsina-des.jpg',
      marketCap: '2.63b',
      earnings: '12.00x',
      dividendYield: 'N/A',
      avgTradedValue: '39.41m',
      price: 2.61,
      eps: 0.21,
      valueToday: '12.25m',
      increaseAverage: 2.76,increaseEGP: 0.07),
  CompanyModel(
      companyName: 'Delta Sugar',
      shortName: 'SUGAR',
      image: 'images/deltasugar.jpg',
      descriptionImage: 'images/sugardelta-des.jpg',
      marketCap: '8.53b',
      earnings: '5.36x',
      dividendYield: 'N/A',
      avgTradedValue: '32.84m',
      price: 59.98,
      eps: 11.19,
      valueToday: '5.75m',
      decreaseAverage: -0.03,
      decreaseEGP: 0.02),
];
